### ISSUE TITLE
Live Demo down

### ISSUE THREAD

**Issue by luisampuerovalenzuela** [nivaldomartinez/link-prevue-demo#2]
Hello,

Your live demo is down!

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/96737011/170099010-9abcfc56-6266-4fac-941b-1b55fdfe5166.png">

Regards

**Comment by nivaldomartinez** [comment]
Hello @luisampuerovalenzuela  the heroku app is no longer available.
but feel free to fork and deploy your own
